### ISSUE TITLE
the game doesn't work

### ISSUE THREAD

**Issue by thisizkp** [rdavison/llama-snake#6]
link: http://192.241.133.216/projects/websnake/index.html
browser: chrome v64 beta

I couldn't get the game to run, at least the game isn't responding to any of the keyboard events.

**Comment by rdavison** [comment]
I haven't had any issues running it on the big three desktop browsers.  I believe it might be buggy on mobile browsers (not tested).  Can you paste the exact browser version you're using?  These are the versions I have installed on my computer:

Safari: 11.0.1 (12604.3.5.1.1)
Firefox: 59.0b4 (64-bit)
Chrome: 64.0.3282.119 (Official Build) (64-bit)

**Comment by rdavison** [comment]
Oops, didn't mean to close the issue.

**Comment by liubko** [comment]
![screen shot 2018-04-03 at 12 55 25 pm](https://user-images.githubusercontent.com/4257937/38242782-5c32f350-373e-11e8-93c1-b07073a831ae.png)
doesn't work for me either
